### ISSUE TITLE
Replacing "Lorem Ipsum" with actual text.

### ISSUE THREAD

**Issue by aadhi-i** [DharshiBalasubramaniyam/ice-cream-parlour-website#44] opened 2024-10-02 06:28 UTC
I can replace that dummy text with a proper one. Please assign it to me under gssoc ext and specified level and hacktoberfest.

![Screenshot 2024-10-02 115625](https://github.com/user-attachments/assets/853ddd56-4fd0-4d43-aaff-0ec4c04d68b6)

**Comment by clownfish1805** [comment] 2024-10-02 08:17
@DharshiBalasubramaniyam I would like to work on replacing "Lorem Ipsum" with actual text.

**My plan:**

1. To replace the Loreum ipseum text with meaningful and relevant content.
2. To put down captivating and elegant styles of text following the guidelines of this project.

Please assign me this issue under **GSSOC'24 extended**.

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 10:57
Hi @aadhi-i, The issue is assigned to you... All the best!

**Closed** 2024-10-02 15:26 UTC
Labels: gssoc-ext, level 1, hacktoberfest-accepted
