### ISSUE TITLE
Add a detailed Read Me File explaining the project, technologies and instructions

### ISSUE THREAD

**Issue by Muskan-bhatt249** [DharshiBalasubramaniyam/ice-cream-parlour-website#38] opened 2024-10-02 05:15 UTC
A well-crafted README file is essential for guiding users and contributors through the project, ensuring they understand its purpose, setup, and usage. I would be happy to take the responsibility of creating a detailed and clear README for this project.

**Comment by riyarane46** [comment] 2024-10-02 05:33
hii @DharshiBalasubramaniyam   i believe i can do this task efficiently .could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 05:58
Hi @Muskan-bhatt249, Thank you for creating this issue. The issue is assigned to you. All the best.

**Comment by rutikakengal** [comment] 2024-10-02 07:49
I like to work on it . update Readme file which is essential to understand what project it is . Assign me

**Comment by Muskan-bhatt249** [comment] 2024-10-02 08:07
@DharshiBalasubramaniyam The Read Me File has been updated by me. Please Review all the changes and provide feedback for any necessary changes required.

**Closed** 2024-10-02 10:48 UTC
Labels: gssoc-ext, level 2, hacktoberfest-accepted
