### ISSUE TITLE
correcting the locations in footer (showing same location four times) can you add GSSOC 24 ext label to this 

### ISSUE THREAD

**Issue by devxMani** [DharshiBalasubramaniyam/ice-cream-parlour-website#25] opened 2024-10-01 20:16 UTC
![image](https://github.com/user-attachments/assets/48919bf5-2677-411e-83b3-e2f8f861ff50)

**Comment by devxMani** [comment] 2024-10-01 20:16
assign this task to me .............................

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 01:28
Hi @devxMani , thank you for creating the issue. The issue is assigned to you. All the best.

**Comment by rounakdey6** [comment] 2024-10-02 19:46
can you assign this me ? I really want to work on this project

**Closed** 2024-10-03 01:06 UTC
Labels: gssoc-ext, level 1, hacktoberfest-accepted
