### ISSUE TITLE
change all buttons styles to make it look more attractive 

### ISSUE THREAD

**Issue by AmanKumar1115** [DharshiBalasubramaniyam/ice-cream-parlour-website#43] opened 2024-10-02 06:21 UTC
@DharshiBalasubramaniyam  I want  to work this project as gssoc-ext, hactoberfest contributer.
Can you please assign this to me?

**Comment by vararaghu002** [comment] 2024-10-02 10:54
Interested to work on this project, pls assign to me.

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 10:58
Hi @AmanKumar1115, The issue is assigned to you... All the best!

**Comment by vararaghu002** [comment] 2024-10-02 11:53
Thank you sir

**Comment by rohitsharma2610** [comment] 2024-10-02 14:46
hey, i have great command in front-end development , so i want to work on this and make this site beautiful.

**Comment by rounakdey6** [comment] 2024-10-02 19:44
Sir , i am full stack developer can you please assign this work to me?

**Comment by Kedarnath-Rothe** [comment] 2024-10-03 10:53
Please Assign this issue to me under hactoberfest label

**Closed** 2024-10-03 12:14 UTC
Labels: gssoc-ext, level 1, hacktoberfest-accepted
