### ISSUE TITLE
UI Enhancement: Improve Text Contrast, Icon Alignment

### ISSUE THREAD

**Issue by PremaDongare** [DharshiBalasubramaniyam/ice-cream-parlour-website#37] opened 2024-10-02 05:13 UTC
**Inconsistent Icons:** The phone and email icons are not aligned or styled uniformly. The up and down arrows next to the icons appear to be a rendering issue. Fixing these icons would provide a cleaner look.
**Icon Size and Spacing:** The social media icons are smaller compared to the text, and there’s inconsistent spacing between the icons and the corresponding text (e.g., Facebook, Instagram, Linkedin). Increasing the size of the icons and ensuring even spacing would improve balance.
**Uniformity in Labels:** The label for "Linkedin" should be corrected to "LinkedIn" (capitalize the 'I' to maintain brand name accuracy).
<img width="170" alt="image" src="https://github.com/user-attachments/assets/34732391-18f2-4c48-9332-9c7c80240b03">
**Note:** I'd love to take on this issue and make the website look even cooler! Please assign it to me.

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 11:02
@PremaDongare, The issue is assigned to you. All the best.

**Comment by PremaDongare** [comment] 2024-10-02 11:30
Okk👍

**Closed** 2024-10-13 00:32 UTC
Labels: gssoc-ext, level1, hacktoberfest-accepted
