### ISSUE TITLE
Animated slider on home section

### ISSUE THREAD

**Issue by Arushi-N4** [DharshiBalasubramaniyam/ice-cream-parlour-website#16] opened 2024-10-01 16:00 UTC
As part of GSSOC EXD 2024, I would like to add an animated slider in the home section of the website. The feature would allow users to click on 3-4 ice cream options on slider, and the background color of the home section would change dynamically based on the selected realm. Also ice cream that user clicked will be displayed.

It will add visual appeal.

![ICE](https://github.com/user-attachments/assets/2dad0d0c-f73a-4ec4-ac94-465e92370522)

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-01 16:17
Hi @Arushi-N4, Thank you for creating this issue. The issue is assigned to you. 

Please make sure that the home page is responsive.
Kindly create a seperate script file for this `script/home`

**Comment by Swarali1107** [comment] 2024-10-01 17:21
I would also like to work on UI UX designing of the website...Can you also assign this task to me

**Closed** 2024-10-06 10:04 UTC
Labels: gssoc-ext, level1, hacktoberfest-accepted
