### ISSUE TITLE
Customer engagement and building catering business as well!

### ISSUE THREAD

**Issue by isnehamondal** [DharshiBalasubramaniyam/ice-cream-parlour-website#26] opened 2024-10-01 20:26 UTC
I am Sneha Mondal, GSSoC'24 Extd.

ISSUE:
I have an idea that we can further update the catering part.

WHAT I CAN DO?
We can make a separate page for it and show what our catering business provides to our customers. Like custom made ice creams like how small children are interested to have icecreams with different flavours, or design. 
I am adding some inspirations below.
![download1](https://github.com/user-attachments/assets/83d3509d-7cb1-47a9-b0e7-84d7d8a2dcfb)
![download2](https://github.com/user-attachments/assets/9e932ff7-3035-4115-8da2-fc1c513b71ad)
![download3](https://github.com/user-attachments/assets/d28ed1ea-20ee-4290-bf4b-f4607aa4e62a)

Also, we can ask what is the event to the customer as you have already mentioned and provide a place for them to enter their requirement. In this way, we can involve the customer and look after their needs and grow the catering business as well by showcasing what we can provide.

I would love to work on this. If you like this idea, please assign this task to me and add the corresponding labels to it.

**Comment by DharshiBalasubramaniyam** [comment] 2024-10-02 01:37
Hi @isnehamondal , thank you for creating the issue. The issue is assigned to you. All the best.

**Closed** 2024-10-06 10:05 UTC
Labels: gssoc-ext, level2, hacktoberfest-accepted
